/**
 * Copyright 2014 -
 * Licensed under the Academic Free License version 3.0
 * http://opensource.org/licenses/AFL-3.0
 * 
 * Authors: Alex Verkhovtsev
 */

package localolympics.db;

import java.util.List;


import com.google.appengine.api.datastore.DatastoreService;
import com.google.appengine.api.datastore.DatastoreServiceFactory;
import com.google.appengine.api.datastore.Entity;
import com.google.appengine.api.datastore.FetchOptions;
import com.google.appengine.api.datastore.Key;
import com.google.appengine.api.datastore.KeyFactory;
import com.google.appengine.api.datastore.Query;
import com.google.appengine.api.datastore.Transaction;


/**
 * GAE ENTITY UTIL CLASS: "Record" <br>
 * PARENT: NONE <br>
 * KEY: A long Id generated by GAE <br>
 * FEATURES: <br>
 * - "time" a {@link String} with the time record for the record<br>
 */

public class Record {

	//
	// SECURITY
	//

	/**
	 * Private constructor to avoid instantiation.
	 */
	private Record() {
	}

	//
	// KIND
	//

	/**
	 * The name of the Permit ENTITY KIND used in GAE.
	 */
	private static final String ENTITY_KIND = "Record";

	//
	// KEY
	//

	/**
	 * Return the Key for a given Permit id given as String.
	 * 
	 * @param recordID A string with the record ID (a long).
	 * @return the Key for this recordID.
	 */
	public static Key getKey(String recordID) {
		long id = Long.parseLong(recordID);
		Key recordKey = KeyFactory.createKey(ENTITY_KIND, id);
		return recordKey;
	}

	/**
	 * Return the string ID corresponding to the key for the permit.
	 * 
	 * @param record The GAE Entity storing the record.
	 * @return A string with the record ID (a long).
	 */
	public static String getStringID(Entity record) {
		return Long.toString(record.getKey().getId());
	}

	//
	// Time
	//

	/**
	 * The property time for the <b>time</b> value of the record.
	 */
	private static final String TIME_PROPERTY = "Time";

	/**
	 * Return the time for the record.
	 * 
	 * @param record The GAE Entity storing the time
	 * @return the time in the record.
	 */
	public static String getTime(Entity record) {
		Object time = record.getProperty(TIME_PROPERTY);
		if (time == null)
			time = "test";
		return (String) time;
	}

	

	//
	// CREATE RECORD
	//

	/**
	 * Create a new record if the recordID is correct and none exists with this id.
	 * 
	 * @param recordTime The time for this record.
	 * @return the Entity created with this id or null if error
	 */
	public static Entity createRecord(String recordTime) {
		Entity record = null;
		DatastoreService datastore = DatastoreServiceFactory.getDatastoreService();
		Transaction txn = datastore.beginTransaction();
		try {

			record = new Entity(ENTITY_KIND);
			record.setProperty(TIME_PROPERTY, recordTime);
			datastore.put(record);

			txn.commit();
		} catch (Exception e) {
			return null;
		} finally {
			if (txn.isActive()) {
				txn.rollback();
			}
		}

		return record;
	}

	//
	// GET RECORD
	//

	/**
	 * Get the record based on a string containing its long ID.
	 * 
	 * @param recordID a {@link String} containing the ID key (a <code>long</code> number)
	 * @return A GAE {@link Entity} for the Record or <code>null</code> if none or error.
	 */
	public static Entity getRecord(String recordID) {
		Entity record = null;
		try {
			DatastoreService datastore = DatastoreServiceFactory.getDatastoreService();
			long id = Long.parseLong(recordID);
			Key recordKey = KeyFactory.createKey(ENTITY_KIND, id);
			record = datastore.get(recordKey);
		} catch (Exception e) {
			// TODO log the error
		}
		return record;
	}


	//
	// UPDATE RECORD
	//

	/**
	 * Update the current description of the record
	 * 
	 * @param recordID A string with the record ID (a long).
	 * @param time The time of the record as a String.
	 * @return true if succeed and false otherwise
	 */
	public static boolean updateRecord(String recordID, String time) {
		Entity record = null;
		try {
			record = getRecord(recordID);
			record.setProperty(TIME_PROPERTY, time);
			DatastoreService datastore = DatastoreServiceFactory.getDatastoreService();
			datastore.put(record);
		} catch (Exception e) {
			return false;
		}
		return true;
	}

	//
	// DELETE RECORD
	//

	/**
	 * Delete the record if not linked to anything else.
	 * 
	 * @param recordID A string with the record ID (a long).
	 * @return True if succeed, false otherwise.
	 */
	public static boolean deleteRecord(String recordID) {
		try {
			DatastoreService datastore = DatastoreServiceFactory.getDatastoreService();
			datastore.delete(getKey(recordID));
		} catch (Exception e) {
			return false;
		}
		return true;
	}

	//
	// QUERY RECORD
	//

	/**
	 * Return the requested number of records (e.g. 100).
	 * 
	 * @param limit The number of records to be returned.
	 * @return A list of GAE {@link Entity entities}.
	 */
	public static List<Entity> getFirstRecords(int limit) {
		DatastoreService datastore = DatastoreServiceFactory.getDatastoreService();
		Query query = new Query(ENTITY_KIND);
		List<Entity> result = datastore.prepare(query).asList(FetchOptions.Builder.withLimit(limit));
		return result;
	}

}
